<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MitarbeiterTbl">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Mitarbeiter" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:integer"/>
              <xs:element name="Vorname" type="xs:string"/>
              <xs:element name="Nachname" type="xs:string"/>
              <xs:element name="Strasse" type="xs:string"/>
              <xs:element name="HausNr" type="xs:integer"/>
              <xs:element name="PLZ" type="xs:integer"/>
              <xs:element name="Ort" type="xs:string"/>
              <xs:element name="Telefon" type="xs:string" minOccurs="0"/>
              <xs:element name="eMail" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ExMitarbeiterTbl">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ExMitarbeiter" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:integer"/>
              <xs:element name="Vorname" type="xs:string"/>
              <xs:element name="Nachname" type="xs:string"/>
              <xs:element name="Strasse" type="xs:string"/>
              <xs:element name="HausNr" type="xs:integer"/>
              <xs:element name="PLZ" type="xs:integer"/>
              <xs:element name="Ort" type="xs:string"/>
              <xs:element name="Telefon" type="xs:string" minOccurs="0"/>
              <xs:element name="eMail" type="xs:string" minOccurs="0"/>
              <xs:element name="Firma" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="KundenTbl">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Kunde" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID" type="xs:integer"/>
              <xs:element name="Vorname" type="xs:string"/>
              <xs:element name="Nachname" type="xs:string"/>
              <xs:element name="Strasse" type="xs:string"/>
              <xs:element name="HausNr" type="xs:integer"/>
              <xs:element name="PLZ" type="xs:integer"/>
              <xs:element name="Ort" type="xs:string"/>
              <xs:element name="Telefon" type="xs:string" minOccurs="0"/>
              <xs:element name="eMail" type="xs:string" minOccurs="0"/>
              <xs:element name="Branche" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema> 